apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-nttdata
spec:
  replicas: 1
  selector: 
      matchLabels: 
        app: hello-nttdata
  template:
    metadata:
      labels:
        app: hello-nttdata
    spec:
      containers:
        - name: hello-nttdata
          image: index.docker.io/nttalok/hello-ntt-data:latest
          ports:
          - containerPort: 80
      
---
apiVersion: v1
kind: Service
metadata:
  name: hello-nttdata-service
spec:
  ports:
    # Accept traffic sent to port 80
    - name: http
      port: 80
      targetPort: 80
  selector:
    app: hello-nttdata
  type: NodePort
